"""empty message

Revision ID: c065e5a5cecf
Revises: f60cb2f96fd2
Create Date: 2025-10-26 13:59:35.736576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c065e5a5cecf'
down_revision = 'f60cb2f96fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_collaborators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=10), nullable=True))
        batch_op.drop_column('permission')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_collaborators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permission', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.drop_column('role')

    # ### end Alembic commands ###
