"""empty message

Revision ID: f60cb2f96fd2
Revises: e32398d42134
Create Date: 2025-10-17 21:50:36.897418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f60cb2f96fd2'
down_revision = 'e32398d42134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_token', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('write_token', sa.String(length=32), nullable=True))
        batch_op.create_unique_constraint(None, ['read_token'])
        batch_op.create_unique_constraint(None, ['write_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('write_token')
        batch_op.drop_column('read_token')

    # ### end Alembic commands ###
